### PR TITLE
jquery 1.5.2, 1.6, and 1.6.1 added for unit testing.  Chrome unit testing gotcha.

### PR DESCRIPTION
**Pull request by dragthor**
Added jquery testing versions 1.5.2, 1.6, 1.6.1.  Chrome -enable-file-cookies flag reminder for testing in ReadMe.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Thanks!

**Comment by dragthor** [comment]
Any ideas for this project? Cookie size checking? Expire other than
whole days? Additional test cases? Funky characters (even though in
theory encodeUri should handle it)?

I can also try to help out with mockajax and amplify too (time permitting).
- kk

On Wednesday, June 8, 2011, scottgonzalez
reply@reply.github.com
wrote:

> Thanks!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/appendto/jquery-jsoncookie/pull/1#issuecomment-1326292

## 

Kris Krause

**Comment by scottgonzalez** [comment]
We should probably do something when you hit the limit to make sure we get consistent results across all browsers. Expiration is already in milliseconds. If there are meaningful test cases to add, we'll certainly accept them.

**Comment by dragthor** [comment]
Your are correct - the now() function uses getTime (for some reason I thought it used getDate).  If a cookie is over the max size - throw an exception?  Set the value to null?

**Comment by scottgonzalez** [comment]
We should probably call `jQuery.error()` if it exists and throw otherwise.

**Comment by dragthor** [comment]
I have a working version (and unit test) with latest Chrome.  If the cookie is too big, then its not saved and $.error("cookie too big") is thrown.  For older jQuery versions, just a regular throw error.

**Comment by dragthor** [comment]
Unit test - https://gist.github.com/1015081

**Comment by dragthor** [comment]
Changes committed to my fork - https://github.com/dragthor/jquery-jsoncookie/commit/655203df3c25fe724eeb14112411ea689ac5b743

 Testing passed against all major release versions of jquery (I guess I should really do all of them).  Chrome 12.0.742.91, FF 4.0., Safari 5.05, and IE 9,8, & 7.  IE6 w/IETester.

**Pull request merged**
